export const Initialize        = "Initialize"
export const StartNewGame      = "StartNewGame"
export const SetCurrentStep    = "SetCurrentStep"
export const AddPlayerAction   = "AddPlayerAction"
export const FirebaseUpdateKey = "FirebaseUpdateKey"
export const CleanupFirebase   = "CleanupFirebase"
